content(performance): don't call functions from the template to get data
typebytes/angular-checklist pull request #97
Opened 2021-11-06 20:22 UTC by MaciejWWojcik

Add new content in the performance category about performance issues as a result of calling functions directly from the template

2022-01-21 20:34 UTC, PooSham requested changes
You seem to have forgotten to add `changeDetection: ChangeDetectionStrategy.OnPush` in the "Using OnPush change Detection strategy" section. 

Also, we should probably change `components/minimize-logic-in-templates.md` too, since it gives the bad advice to do calls from the tempalte

2022-07-02 11:25 UTC, MaciejWWojcik commented
Oh, thanks! I updated the pull request with missing ChangeDetection line :)

2022-09-19 17:53 UTC, d3lm requested changes
Love it! Thanks for the PR 🙏 Left some remarks.

2022-09-19 17:53 UTC, d3lm commented on content/performance/dont-call-function-from-template.md
> +## Using OnPush Change Detection strategy
```suggestion
## Using OnPush change detection strategy
```

2022-09-19 17:53 UTC, d3lm commented on content/performance/dont-call-function-from-template.md
> +Change Detection strategy describes how Angular should handle Change Detection and DOM rendering. When using OnPush strategy, the function will be called again only if `@Input` properties changes, or
```suggestion
The change detection strategy describes how Angular should handle change detection. When using the `OnPush` strategy, change detection only runs if an `@Input` property changes, event are emitted e.g. an `@Output`, or an `Observable` emits new values. Furthermore, change detection can be executed manually via the `ChangeDetectorRef`.
```

2022-09-19 17:53 UTC, d3lm commented on content/performance/dont-call-function-from-template.md
> +Pipes by default are pure, which means Angular will execute its `transform` method only on change to the input value.
Newline before.

2022-09-19 17:53 UTC, d3lm commented on content/performance/dont-call-function-from-template.md
> +Change Detection strategy describes how Angular should handle Change Detection and DOM rendering. When using OnPush strategy, the function will be called again only if `@Input` properties changes, or
See https://angular.io/api/core/ChangeDetectorRef#!#detectChanges-anchor

2022-09-19 17:53 UTC, d3lm commented on content/performance/dont-call-function-from-template.md
> +Given that example:
Newline before, and:

```suggestion
Here's an example:
```

2022-09-19 17:53 UTC, d3lm commented on content/performance/dont-call-function-from-template.md
> +As long as the `id` property will stay the same, the pipe won't execute its code again and perform a possibly expensive task.
```suggestion
As long as the `id` property doesn't change the pipe won't execute its code again and perform a possibly expensive task.
```

2022-09-19 17:53 UTC, d3lm commented on content/performance/dont-call-function-from-template.md
> +
Remove one newline.

2022-09-22 10:59 UTC, MaciejWWojcik commented
Thank you for the remarks and suggestions! Now it looks a way better 😄 🙏

2022-09-26 08:15 UTC, d3lm approved these changes

2022-09-26 08:15 UTC, merged

2022-09-26 08:15 UTC, d3lm commented
Good job! Thanks for the PR 🙏